language: php

sudo: false

php:
  - 7.2

install:
  - composer global require drush/drush:8.x-dev drupal/coder mglaman/drupal-check friendsoftwig/twigcs
  - export PATH="$HOME/.config/composer/vendor/bin:$PATH"
  - phpenv rehash
  # Downloading drupal core.
  - cd ../ && drush dl drupal-8 --drupal-project-rename=drupal
  - cd drupal
  - composer install
  # Preparing PHPUnit for run tests.
  - composer run-script drupal-phpunit-upgrade
  - export DRUPAL_ROOT=$(pwd)
  - export SIMPLETEST_BASE_URL="http://127.0.0.1:8080"
  - export SIMPLETEST_DB="sqlite://tmp/site.sqlite"
  - export PATH="$DRUPAL_ROOT/vendor/bin:$PATH"
  # Adding os2forms as package from local system.
  - export REPOSITORIES='"repositories":\ \['
  - export REPOSITORIES_REPLACE='"repositories":\[\{"type":"path","url":"..\/os2forms","options":\{"symlink":false\}\},'
  - export REQUIRE='"require":\ {'
  - export REQUIRE_REPLACE='"require":{"os2forms\/os2forms":"\*",'
  - sed -i "s/$REPOSITORIES/$REPOSITORIES_REPLACE/g" composer.json
  - sed -i "s/$REQUIRE/$REQUIRE_REPLACE/g" composer.json
  - composer update os2forms/os2forms
  - PROJECT_PATH=$DRUPAL_ROOT/modules/contrib/os2forms
  # Install Drupal core node packages.
  - nvm install node
  - nvm use node
  - npm install --global yarn eslint-config-drupal-bundle stylelint
  - cd $DRUPAL_ROOT/core
  - yarn install
  # Set Drupal code standards for Code Sniffer.
  - phpcs --config-set installed_paths ../../drupal/coder/coder_sniffer

script:
  - cd $DRUPAL_ROOT/core
  - phpunit ../modules/contrib/webform/tests
  - phpcs --standard=Drupal --ignore=*.md $PROJECT_PATH
  - twigcs $PROJECT_PATH
  - eslint $PROJECT_PATH
  - stylelint --aei $PROJECT_PATH/**/*.css
  - drupal-check $PROJECT_PATH
